backend:
  name: git-gateway
  branch: main

media_folder: "image"

collections:
  - name: "evenements"
    label: "Événements"
    files:
      - label: "Prochains événements"
        name: "evenements"
        file: "data/evenements.json"
        fields:
          - label: "Événements"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titre", name: "titre", widget: "string"}
              - {label: "Date", name: "date", widget: "string"}
              - {label: "Lieu", name: "lieu", widget: "string"}

  - name: "brocante"
    label: "Prochaine Brocante"
    files:
      - label: "Infos brocante"
        name: "brocante"
        file: "data/brocante.json"
        fields:
          - {label: "Titre", name: "titre", widget: "string"}
          - {label: "Date", name: "date", widget: "string"}
          - {label: "Horaires", name: "horaires", widget: "string"}
          - {label: "Lieu", name: "lieu", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "contact"
    label: "Informations Contact"
    files:
      - label: "Contact"
        name: "contact"
        file: "data/contact.json"
        fields:
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Téléphone", name: "telephone", widget: "string"}
          - {label: "Adresse", name: "adresse", widget: "string"}

  - name: "ticker"
    label: "Bandeau défilant"
    files:
      - label: "Ticker"
        name: "ticker"
        file: "data/ticker.json"
        fields:
          - label: "Messages"
            name: "messages"
            widget: "list"
            fields:
              - {label: "Message", name: "texte", widget: "string"}